include: package:flutter_lints/flutter.yaml

analyzer:
  plugins:
    - custom_lint
  exclude:
    - "**/*.freezed.dart"
    - "**/*.g.dart"
    - "build/**"

linter:
  rules:
    prefer_single_quotes: true
